core/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'^check/?$', views.CheckView.as_view(), name='check'),
    re_path(r'^check/map/?$', views.MapView.as_view(), name='map'),
    re_path(r'^report/?$', views.ReportView.as_view(), name='report'),
    re_path(r'^report/confirmation/(?P<upload_id>[0-9a-f-]{36})/?$', views.ReportConfirmationView.as_view(), name='report-confirmation'),
    re_path(r'^delete/?$', views.DeleteView.as_view(), name='delete'),
    re_path(r'^delete/confirmation/?$', views.DeleteConfirmationView.as_view(), name='delete-confirmation'),
]

howimetcorona/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import include


urlpatterns = [
    path('', include(('core.urls', 'core'), namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class VisitedPoint(BaseModel):
    lat = models.DecimalField(max_digits=10, decimal_places=7)
    lng = models.DecimalField(max_digits=10, decimal_places=7)
    visited_at = models.DateTimeField()
    is_verified = models.BooleanField(default=False)
    upload_id = models.CharField(max_length=36, null=True)

core/forms.py
from django import forms


class BaseFileForm(forms.Form):
    # we try to minify the file to only submit the data
    points_file = forms.FileField(
        required=False,
        widget=forms.FileInput(attrs={'required': 'required'}),
        label="Location History File (.json)"
    )
    points_data = forms.CharField(widget=forms.HiddenInput(), required=False)

    def clean(self):
        points_file = self.cleaned_data.get('points_file')
        points_data = self.cleaned_data.get('points_data')

        if not points_file and not points_data:
            raise forms.ValidationError({'points_file': 'File is required.'})

        return self.cleaned_data


class ReportForm(BaseFileForm):
    symptoms_at = forms.DateField(widget=forms.TextInput(attrs={
        'placeholder': 'YYYY-MM-DD',
        'pattern': '[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}',
        'title': 'YYYY-MM-DD'
    }))
    is_verified = forms.BooleanField(required=False)


class CheckForm(BaseFileForm):
    pass


class DeleteForm(forms.Form):
    delete_token = forms.CharField(label="Delete token")

core/views.py
from datetime import datetime, timedelta
import json
import uuid

from django.contrib import messages
from django.views.generic import TemplateView, FormView
from django.db import transaction
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.db.models import Q

from .models import VisitedPoint
from . import forms


POINTS_SESSION_KEY = 'points'
RISK_SESSION_KEY = 'risk_points'
MAX_POINTS = 1000
LAT_METER = 0.000009
LNG_METER = 0.0000146


class JsDataMixin:
    def __init__(self):
        self._js_data = {}

    def add_data(self, key, data):
        self._js_data[key] = data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['js_data'] = json.dumps(self._js_data)
        return context


class HomeView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hide_logo_menu'] = True
        return context


def import_google_coordinate(lat, lng):
    return lat*1e-7, lng*1e-7


def import_timeline_objects(data):
    visited_points = []

    timeline_objects = data['timelineObjects']
    for timeline_object in timeline_objects:
        if 'placeVisit' in timeline_object:
            place_visit = timeline_object['placeVisit']
            # TODO@Glumli: smart way to handle durations
            duration = place_visit['duration']
            start_timestamp = int(duration['startTimestampMs']) / 1000
            end_timestamp = int(duration['endTimestampMs']) / 1000
            visited_at = datetime.fromtimestamp((start_timestamp + end_timestamp) / 2)

            location = place_visit['location']
            lat, lng = import_google_coordinate(location['latitudeE7'], location['longitudeE7'])

            visited_points.append({
                'lat': lat,
                'lng': lng,
                'visited_at': visited_at
            })
        elif 'activitySegment' in timeline_object:
            activity_segment = timeline_object['activitySegment']

            duration = activity_segment['duration']

            start_timestamp = int(duration['startTimestampMs']) / 1000
            end_timestamp = int(duration['endTimestampMs']) / 1000
            if 'waypointPath' in activity_segment:
                visited_at = datetime.fromtimestamp((start_timestamp + end_timestamp) / 2)

                waypoint_path = activity_segment['waypointPath']
                points = waypoint_path.get('waypoints', [])
                for point in points:
                    lat, lng = import_google_coordinate(point['latE7'], point['lngE7'])
                    visited_points.append({
                        'lat': lat,
                        'lng': lng,
                        'visited_at': visited_at
                    })
            elif 'simplifiedRawPath' in activity_segment:
                simplified_path = activity_segment['simplifiedRawPath']
                points = simplified_path.get('points', [])
                for point in points:
                    lat, lng = import_google_coordinate(point['latE7'], point['lngE7'])
                    visited_at = datetime.fromtimestamp(int(point['timestampMs']) / 1000)
                    visited_points.append({
                        'lat': lat,
                        'lng': lng,
                        'visited_at': visited_at
                    })
            elif 'transitPath' in activity_segment:
                visited_at = datetime.fromtimestamp((start_timestamp + end_timestamp) / 2)

                transit_path = activity_segment['transitPath']
                points = transit_path.get('transitStops', [])
                for point in points:
                    lat, lng = import_google_coordinate(point['latitudeE7'], point['longitudeE7'])
                    visited_points.append({
                        'lat': lat,
                        'lng': lng,
                        'visited_at': visited_at
                    })
            else:
                start_point = activity_segment['startLocation']
                lat, lng = import_google_coordinate(start_point['latitudeE7'], start_point['longitudeE7'])
                visited_at = datetime.fromtimestamp(start_timestamp)

                visited_points.append({
                    'lat': lat,
                    'lng': lng,
                    'visited_at': visited_at
                })

                end_point = activity_segment['endLocation']
                lat, lng = import_google_coordinate(end_point['latitudeE7'], end_point['longitudeE7'])
                visited_at = datetime.fromtimestamp(end_timestamp)

                visited_points.append({
                    'lat': lat,
                    'lng': lng,
                    'visited_at': visited_at
                })
    return visited_points


def import_location_history(data, is_check=False):
    visited_points = []
    locations = data['locations']

    for location in locations:
        lat, lng = import_google_coordinate(location['latitudeE7'], location['longitudeE7'])
        visited_point = {
            'lat': lat,
            'lng': lng,
            'visited_at': datetime.fromtimestamp(int(location['timestampMs'])/1000)
        }
        if is_check:
            visited_point['accuracy'] = location['accuracy']
        visited_points.append(visited_point)

    return visited_points


class ReportView(FormView):
    form_class = forms.ReportForm
    template_name = 'core/report_form.html'

    def get_success_url(self):
        return reverse('core:report-confirmation', args=(self.upload_id,))

    @transaction.atomic
    def form_valid(self, form):
        # add points to db
        raw_data = form.cleaned_data['points_data']
        first_symptoms_date = form.cleaned_data['symptoms_at']
        first_symptoms_datetime = datetime(
            year=first_symptoms_date.year,
            month=first_symptoms_date.month,
            day=first_symptoms_date.day,
        )
        infectious_datetime = first_symptoms_datetime - timedelta(days=2)

        if not raw_data:
            raw_data = form.cleaned_data['points_file'].read()

        self.upload_id = str(uuid.uuid4())
        visited_points = []
        points = import_location_history(json.loads(raw_data))
        for point in points:
            if infectious_datetime > point['visited_at']:
                continue
            visited_points.append(
                VisitedPoint(
                    lat=point['lat'],
                    lng=point['lng'],
                    visited_at=point['visited_at'],
                    is_verified=form.cleaned_data['is_verified'],
                    upload_id=self.upload_id,
                )
            )
        VisitedPoint.objects.bulk_create(visited_points)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Report Infected Points'
        return context


class ReportConfirmationView(TemplateView):
    template_name = 'core/report_confirmation.html'


class CheckView(FormView):
    form_class = forms.CheckForm
    template_name = 'core/check_form.html'
    success_url = reverse_lazy('core:map')

    def form_valid(self, form):
        # compute risk on the fly
        raw_data = form.cleaned_data['points_data']
        if not raw_data:
            raw_data = form.cleaned_data['points_file'].read()

        points = import_location_history(json.loads(raw_data), is_check=True)
        self.request.session[POINTS_SESSION_KEY] = [{
            'lat': float(point['lat']),
            'lng': float(point['lng']),
            'visited_at': str(point['visited_at']),
        } for point in points]

        filters = None
        time_window = timedelta(minutes=20)

        for point in points:
            min_date = point['visited_at'] - time_window
            max_date = point['visited_at'] + time_window

            lat_radius = 20 * LAT_METER
            lng_radius = 20 * LNG_METER

            if filters is None:
                filters = Q(
                    lat__gt=point['lat'] - lat_radius,
                    lat__lt=point['lat'] + lat_radius,
                    lng__gt=point['lng'] - lng_radius,
                    lng__lt=point['lng'] + lng_radius,
                    visited_at__gt=min_date,
                    visited_at__lt=max_date
                )
            else:
                filters |= Q(
                    lat__gt=point['lat'] - lat_radius,
                    lat__lt=point['lat'] + lat_radius,
                    lng__gt=point['lng'] - lng_radius,
                    lng__lt=point['lng'] + lng_radius,
                    visited_at__gt=min_date,
                    visited_at__lt=max_date
                )

        risk_points = list(VisitedPoint.objects.filter(filters)) if filters else []

        self.request.session[RISK_SESSION_KEY] = [{
            'lat': float(point.lat),
            'lng': float(point.lng),
            'visited_at': str(point.visited_at),
        } for point in risk_points]

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Check Your Points'
        return context


class MapView(JsDataMixin, TemplateView):
    template_name = 'core/map.html'

    def dispatch(self, request, *args, **kwargs):
        # map should only show results from check
        self._points = self.request.session.get(POINTS_SESSION_KEY, [])
        if not self._points:
            messages.warning(request, 'No valid location points found in your file.')
            return HttpResponseRedirect(reverse('core:check'))

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.add_data('points', self._points)

core/templates/core/base.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>How I met Corona</title>
        {% block styles %}{% endblock %}
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

        {% if js_data %}
        <script>
            window.data = {{ js_data|safe }};
        </script>
        {% endif %}

        {% block head %}{% endblock %}
    </head>
    <body>
        <div class="wrapper">
            <div class="menu">
                {% if not hide_logo_menu %}
                    <div class="logo-container logo-container--small">
                        <a href="{% url 'core:home' %}">
                            <img src="{% static 'images/world_map.png' %}" class="logo-container__logo logo-container__logo--small" />
                        </a>
                    </div>
                {% endif %}
                <a class="menu__item" href="{% url 'core:home' %}">Home</a>
            </div>

            {% block content %}{% endblock %}

            <div class="footer">
                <a class="footer__link" href="{% url 'core:delete' %}">Delete my data</a>&emsp;|&emsp;<a class="footer__link" href="https://nico.is/impressum/" target="_blank">Imprint</a>
            </div>
        </div>
    </body>
</html>

core/templates/core/check_form.html
{% extends 'core/form.html' %}

core/templates/core/delete_confirmation.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
     <div class="logo-wrapper">
        <div class="logo-container logo-container--success">
            <img src="{% static 'images/thank_you.png' %}" class="logo-container__logo" />
        </div>
         <h3 class="logo-wrapper__title logo-wrapper__title--success">
             Your data has been removed
         </h3>
         <p>You can re-upload your data at any time.</p>
    </div>
{% endblock content %}

core/templates/core/delete_form.html
{% extends 'core/form.html' %}

{% block head %}{% endblock %}

core/templates/core/form.html
{% extends 'core/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock styles %}

{% block head %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'scripts/truncate_file.js' %}"></script>
    <script src="{% static 'scripts/datepicker.js' %}"></script>
    <script src="{% static 'scripts/fileupload.js' %}"></script>
{% endblock %}

{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="message message--{{ message.level }}">
                {{ message.message }}
            </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="form__wrapper">
        <form class="form{% if not form.visible_fields %} form--hidden{% endif %}" method="post"
              enctype="multipart/form-data">
            <h3 class="form__title">{{ title }}</h3>

            <div class="django-form">
                <div class="form__fields">
                    {% if form.non_field_errors %}
                        <div class="form__field form__field--error">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}

                    {% for field in form %}
                        {% if field.field.widget.input_type == 'file' %}
                            <label for="id_{{ field.name }}">
                                {{ field.label }}
                                <a class="file-info" href="https://takeout.google.com/settings/takeout/custom/location_history" target="_blank">
                                </a>
                            </label>

                            <div class="file-upload">
                                <div class="file-upload-wrap">
                                    <input class="file-upload-input" required id="id_{{ field.name }}" name="{{ field.name }}" type="file" onchange="readURL(this);"/>
                                    <div class="drag-text">
                                        Drag and drop a file
                                    </div>
                                </div>
                                <div class="file-upload-content">
                                    <div class="file-title-wrap">
                                        <span class="file-title">Uploaded File</span>
                                        <button type="button" onclick="removeUpload()" class="remove-file">Remove
                                        </button>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="form__field{% if field.errors %} form__field--error{% endif %}{% if field.is_hidden %} form__field--hidden{% endif %}{% if field.field.required %} form__field--required{% endif %}">
                                {% if not field.is_hidden %}
                                    {{ field.label_tag }}
                                {% endif %}

                                {% if field.name == 'symptoms_at' %}
                                    <input type="text" id="id_{{ field.name }}" name="{{ field.name }}" size="30" placeholder="YYYY-MM-DD" autocomplete="off" required>
                                {% else %}
                                    {{ field }}
                                {% endif %}

                                {% if not field.is_hidden %}
                                    {{ field.errors }}
                                {% endif %}

                                {% if not field.is_hidden and field.help_text %}
                                    <div class="field__note">
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

            {% csrf_token %}

            <div class="button-bar">
                {% block form_buttons %}
                    <input class="button button--form" type="submit" name="_submit" value="Submit">
                {% endblock %}
            </div>
        </form>
    </div>
{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="home">
        <div class="logo-wrapper">
            <div class="logo-container">
                <img src="{% static 'images/world_map.png' %}" class="logo-container__logo" />
            </div>
            <h4 class="logo-wrapper__title">How I Met Corona</h4>
        </div>

        <div class="home__intro">
            <p>
                <b>Did I have contact with an infected person in the last two weeks? <br>
                    "How I met Corona" uses existing data to get a little closer to the answer.</b>
            </p>

            <p>
                If you got infected with the corona virus you can anonymously upload <br>
                your last 14 days of location data points here. Other people can then<br>
                compare their data to see if your paths crossed at any point in time.
            </p>
        </div>

        <div class="home__cta">
            <a href="{% url 'core:report' %}" class="button">Report infected points</a>
            <a href="{% url 'core:check' %}" class="button">Check your points</a>
        </div>
    </div>
{% endblock %}

core/templates/core/map.html
{% extends 'core/base.html' %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'styles/leaflet.css' %}"/>
    <link rel="stylesheet" href="{% static 'styles/MarkerCluster.css' %}"/>
    <link rel="stylesheet" href="{% static 'styles/MarkerCluster.Default.css' %}"/>
    <script src="{% static 'scripts/leaflet.min.js' %}"></script>
    <script src="{% static 'scripts/leaflet.markercluster.js' %}"></script>
    <script src="{% static 'scripts/map.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="map" class="map"></div>
{% endblock %}

core/templates/core/report_confirmation.html
{% extends 'core/base.html' %}

{% load static %}

{% block head %}
    <script>
      function copyToClipboard() {
        var copyText = document.getElementById("textToCopy");
        var copyBtn = document.getElementById("btnCopy");
        copyText.select();
        copyText.setSelectionRange(0, 99999)
        document.execCommand("copy");
        copyBtn.innerText = 'Copied!';
      }
    </script>
{% endblock %}

{% block content %}
    <div class="logo-wrapper">
        <div class="logo-container logo-container--success">
            <img src="{% static 'images/thank_you.png' %}" class="logo-container__logo"/>
        </div>
        <h3 class="logo-wrapper__title logo-wrapper__title--success">
            Thank You
        </h3>
        <p>
            We really appreciate that you shared your information. <br>
            We hope you'll get better soon!
        </p>

        <p>
            In case you decide to remove your uploaded data later on,
            you can use this key to do so:
        </p>
        <div class="upload-id__wrapper">
            <input id="textToCopy" class="upload-id" value="{{ upload_id }}" readonly width="100%">
            <button onclick="copyToClipboard()" id="btnCopy" class="button button--upload">Copy key</button>
        </div>
        <p>Please store this key somewhere secure.</p>
    </div>

{% endblock content %}

core/templates/core/report_form.html
{% extends 'core/form.html' %}